name: Eingabe Ausgabe Steel Ant
markdown: redcarpet
highlighter: pygments
baseurl: /steel-ant-input-output
exclude: ["examples/**/index.html"]
mail: moron-zirfas@fh-potsdam.de
sass:
  sass_dir: _sass
  style: :compressed
